language: cpp
compiler:
  - gcc
before_install:
  - pip install --user cpp-coveralls
script:
  - ./configure --enable-gcov && mkdir build && cd build && cmake .. && make && make check
after_success:
  - coveralls --exclude lib --exclude tests --gcov-options '\-lp'